services:
  - type: web
    name: srweb
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 25.0.0
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer