services:
  - type: web
    name: srweb
    env: node
    region: oregon
    plan: free
    buildCommand: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true